package com.deardhruv.adaptivelayout.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme - Default
val primaryLight = Color(0xFF00957A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC2F4EA)
val onPrimaryContainerLight = Color(0xFF00201C)
val secondaryLight = Color(0xFF4D635D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E8E0)
val onSecondaryContainerLight = Color(0xFF091F1A)
val tertiaryLight = Color(0xFF466379)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCDE9FF)
val onTertiaryContainerLight = Color(0xFF001F2C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FBF7)
val onBackgroundLight = Color(0xFF171D1B)
val surfaceLight = Color(0xFFF5FBF7)
val onSurfaceLight = Color(0xFF171D1B)
val surfaceVariantLight = Color(0xFFDBE5DF)
val onSurfaceVariantLight = Color(0xFF3F4945)
val outlineLight = Color(0xFF6F7975)
val outlineVariantLight = Color(0xFFBFC9C4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B322F)
val inverseOnSurfaceLight = Color(0xFFECF2EE)
val inversePrimaryLight = Color(0xFF86D6BE)
val surfaceDimLight = Color(0xFFD5DBD7)
val surfaceBrightLight = Color(0xFFFFFFFF) // Changed to pure white for more brightness
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5F1) // Slightly lighter than before
val surfaceContainerLight = Color(0xFFE9EFEB)
val surfaceContainerHighLight = Color(0xFFE3EAE5)
val surfaceContainerHighestLight = Color(0xFFDEE4E0)

// Light Theme - Medium Contrast
val primaryLightMediumContrast = Color(0xFF00705D) // Changed to a darker primary
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF80C4B8) // A bit darker container
val onPrimaryContainerLightMediumContrast = Color(0xFF000000) // Changed to black
val secondaryLightMediumContrast = Color(0xFF3B514B) // Darker secondary
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF809990) // Darker container
val onSecondaryContainerLightMediumContrast = Color(0xFF000000) // Changed to black
val tertiaryLightMediumContrast = Color(0xFF2E4B5E) // Darker tertiary
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF7495AB) // Darker container
val onTertiaryContainerLightMediumContrast = Color(0xFF000000) // Changed to black
val errorLightMediumContrast = Color(0xFFB00020) // Darker error
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF6679) // Darker container
val onErrorContainerLightMediumContrast = Color(0xFF000000) // Changed to black
val backgroundLightMediumContrast = Color(0xFFF5FBF7)
val onBackgroundLightMediumContrast = Color(0xFF171D1B)
val surfaceLightMediumContrast = Color(0xFFF5FBF7)
val onSurfaceLightMediumContrast = Color(0xFF000000) // Changed to black
val surfaceVariantLightMediumContrast = Color(0xFFCED9D4) // Darker surface variant
val onSurfaceVariantLightMediumContrast = Color(0xFF2A3430) // Darker on surface variant
val outlineLightMediumContrast = Color(0xFF57615D)
val outlineVariantLightMediumContrast = Color(0xFF737D78)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B322F)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFFFFF) // Changed to white
val inversePrimaryLightMediumContrast = Color(0xFF00705D)
val surfaceDimLightMediumContrast = Color(0xFFD5DBD7)
val surfaceBrightLightMediumContrast = Color(0xFFFFFFFF) // Changed to pure white
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF0F5F1) // Slightly lighter
val surfaceContainerLightMediumContrast = Color(0xFFE0E9E5) // Darker
val surfaceContainerHighLightMediumContrast = Color(0xFFDADFD9) // Darker
val surfaceContainerHighestLightMediumContrast = Color(0xFFD5D9D5) // Darker

// Light Theme - High Contrast
val primaryLightHighContrast = Color(0xFF004D40) // Changed to very dark primary
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00322B) // Very dark container
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF1A2F2A) // Very dark secondary
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF3B514B) // Very dark container
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF002536)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2E4B5E) // Darker tertiary
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFFB00020) // Darker error
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF860009) // Darker container
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF5FBF7)
val onBackgroundLightHighContrast = Color(0xFF000000) // Changed to black
val surfaceLightHighContrast = Color(0xFFF5FBF7)
val onSurfaceLightHighContrast = Color(0xFF000000) // Changed to black
val surfaceVariantLightHighContrast = Color(0xFFCED9D4) // Darker surface variant
val onSurfaceVariantLightHighContrast = Color(0xFF1A2F2A) // Darker on surface variant
val outlineLightHighContrast = Color(0xFF1A2F2A) // Darker outline
val outlineVariantLightHighContrast = Color(0xFF2A3430) // Darker outline
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF000000) // Changed to black
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF004D40)
val surfaceDimLightHighContrast = Color(0xFFD5DBD7)
val surfaceBrightLightHighContrast = Color(0xFFFFFFFF) // Changed to pure white
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF0F5F1)
val surfaceContainerLightHighContrast = Color(0xFFE0E9E5) // Darker
val surfaceContainerHighLightHighContrast = Color(0xFFDADFD9) // Darker
val surfaceContainerHighestLightHighContrast = Color(0xFFD5D9D5) // Darker

// Dark Theme - Default
val primaryDark = Color(0xFF9FDBCE)
val onPrimaryDark = Color(0xFF003731)
val primaryContainerDark = Color(0xFF005048)
val onPrimaryContainerDark = Color(0xFFC2F4EA)
val secondaryDark = Color(0xFFB4CCCA)
val onSecondaryDark = Color(0xFF1F352F)
val secondaryContainerDark = Color(0xFF354B45)
val onSecondaryContainerDark = Color(0xFFD0E8E0)
val tertiaryDark = Color(0xFFABCCE5)
val onTertiaryDark = Color(0xFF143446)
val tertiaryContainerDark = Color(0xFF2E4B5E)
val onTertiaryContainerDark = Color(0xFFCDE9FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1512)
val onBackgroundDark = Color(0xFFDEE4E0)
val surfaceDark = Color(0xFF0F1512)
val onSurfaceDark = Color(0xFFDEE4E0)
val surfaceVariantDark = Color(0xFF3F4945)
val onSurfaceVariantDark = Color(0xFFBFC9C4)
val outlineDark = Color(0xFF89938E)
val outlineVariantDark = Color(0xFF3F4945)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4E0)
val inverseOnSurfaceDark = Color(0xFF2B322F)
val inversePrimaryDark = Color(0xFF0F6B57)
val surfaceDimDark = Color(0xFF181F1C) // Changed to a slightly darker dim
val surfaceBrightDark = Color(0xFF343B38)
val surfaceContainerLowestDark = Color(0xFF090F0D)
val surfaceContainerLowDark = Color(0xFF171D1B)
val surfaceContainerDark = Color(0xFF1B211F)
val surfaceContainerHighDark = Color(0xFF252B29)
val surfaceContainerHighestDark = Color(0xFF303634)

// Dark Theme - Medium Contrast
val primaryDarkMediumContrast = Color(0xFF80C4B8) // Changed to a slightly lighter primary
val onPrimaryDarkMediumContrast = Color(0xFF000000) // Changed to black
val primaryContainerDarkMediumContrast = Color(0xFF005048)
val onPrimaryContainerDarkMediumContrast = Color(0xFFC2F4EA) //Changed to lighter
val secondaryDarkMediumContrast = Color(0xFFA0C2B9) // Changed to a lighter secondary
val onSecondaryDarkMediumContrast = Color(0xFF000000) // Changed to black
val secondaryContainerDarkMediumContrast = Color(0xFF354B45) // Changed to a darker secondaryContainer
val onSecondaryContainerDarkMediumContrast = Color(0xFFD0E8E0) //Changed to lighter
val tertiaryDarkMediumContrast = Color(0xFF9FC5E0) // Changed to a lighter tertiary
val onTertiaryDarkMediumContrast = Color(0xFF000000) // Changed to black
val tertiaryContainerDarkMediumContrast = Color(0xFF2E4B5E) // Changed to a darker tertiaryContainer
val onTertiaryContainerDarkMediumContrast = Color(0xFFCDE9FF)//Changed to lighter
val errorDarkMediumContrast = Color(0xFFFFB4AB)
val onErrorDarkMediumContrast = Color(0xFF000000) // Changed to black
val errorContainerDarkMediumContrast = Color(0xFF93000A) // Changed to a darker container
val onErrorContainerDarkMediumContrast = Color(0xFFFFDAD6)//Changed to lighter
val backgroundDarkMediumContrast = Color(0xFF0F1512)
val onBackgroundDarkMediumContrast = Color(0xFFFFFFFF) // Changed to white
val surfaceDarkMediumContrast = Color(0xFF181F1C) // Changed to a slightly darker surface
val onSurfaceDarkMediumContrast = Color(0xFFF6FCF8)
val surfaceVariantDarkMediumContrast = Color(0xFF444F4A) // Changed to a slightly darker surface variant
val onSurfaceVariantDarkMediumContrast = Color(0xFFBFC9C4)
val outlineDarkMediumContrast = Color(0xFF9BA5A0)
val outlineVariantDarkMediumContrast = Color(0xFF7B8581)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFFFFFFF) // Changed to white
val inverseOnSurfaceDarkMediumContrast = Color(0xFF0F1512) // Changed to dark
val inversePrimaryDarkMediumContrast = Color(0xFF005048)
val surfaceDimDarkMediumContrast = Color(0xFF181F1C) // Changed to a slightly darker dim
val surfaceBrightDarkMediumContrast = Color(0xFF343B38)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090F0D)
val surfaceContainerLowDarkMediumContrast = Color(0xFF171D1B)
val surfaceContainerDarkMediumContrast = Color(0xFF1B211F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF252B29)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF303634)

// Dark Theme - High Contrast
val primaryDarkHighContrast = Color(0xFFFFFFFF) // Changed to bright white
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF80C4B8)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFFFF) // Changed to bright white
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA0C2B9)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFFFFF) // Changed to bright white
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9FC5E0)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFFFFF) // Changed to bright white
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFB4AB)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF000000) // Changed to pure black
val onBackgroundDarkHighContrast = Color(0xFFFFFFFF) // Changed to pure white
val surfaceDarkHighContrast = Color(0xFF000000) // Changed to pure black
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF) // Changed to pure white
val surfaceVariantDarkHighContrast = Color(0xFF2A3430) // Changed to a darker surface variant
val onSurfaceVariantDarkHighContrast = Color(0xFFF3FDF7)
val outlineDarkHighContrast = Color(0xFFBFC9C4) // Changed to a lighter outline
val outlineVariantDarkHighContrast = Color(0xFFBFC9C4) // Changed to a lighter outline
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFFFFFFF) // Changed to pure white
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000) // Changed to pure black
val inversePrimaryDarkHighContrast = Color(0xFF80C4B8)
val surfaceDimDarkHighContrast = Color(0xFF181F1C) // Changed to a slightly darker dim
val surfaceBrightDarkHighContrast = Color(0xFF343B38)
val surfaceContainerLowestDarkHighContrast = Color(0xFF090F0D)
val surfaceContainerLowDarkHighContrast = Color(0xFF171D1B)
val surfaceContainerDarkHighContrast = Color(0xFF1B211F)
val surfaceContainerHighDarkHighContrast = Color(0xFF252B29)
val surfaceContainerHighestDarkHighContrast = Color(0xFF303634)


val seed = Color(0xFF00957A)

val normalStrokeColor = Color(0xFFCCCCCC)
val dividerDark = Color(0xFF444444)
val facebookBlueColor = Color(0xFF1877F2)
